SELECT VENDOR.VendorName, AVG(PART.PartPrice + MERCHANDISE.MerchPrice / 2) AS "Average Price"
FROM VENDOR
	JOIN PART
	ON VENDOR.ID = PART.VendorID
	JOIN MERCHANDISE
	ON VENDOR.ID = MERCHANDISE.VendorID
WHERE PART.PartPrice > 100
GROUP BY VENDOR.VendorName
--ORDER BY PART.PartPrice DESC